//
//  This file is part of ATLink.
//
//  ATLink is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ATLink is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with ATLink.  If not, see <https://www.gnu.org/licenses/>.
//

#pragma once

#include <array>
#include <optional>
#include <string_view>

#include "atlink/core/Enum.h"
#include "atlink/core/Response.h"
#include "atlink/utils/EnumStringConverter.h"

namespace ATL_NS {
namespace Proto {
namespace Std {

class CmeError : public Core::AResponse {

  public:
    enum class Code {
        PhoneFailure = 0,
        NoConnection = 1,
        LinkReserved = 2,
        NotAllowed = 3,
        NotSupported = 4,
        PhSimPin = 5,
        PhFsimPin = 6,
        PhFsimPuk = 7,
        SimNotInserted = 10,
        SimPin = 11,
        SimPuk = 12,
        SimFailure = 13,
        SimBusy = 14,
        SimWrong = 15,
        IncorrectPassword = 16,
        SimPin2 = 17,
        SimPuk2 = 18,
        MemoryFull = 20,
        InvalidIndex = 21,
        NotFound = 22,
        MemoryFailure = 23,
        TextTooLong = 24,
        InvalidChars = 25,
        DialStringTooLong = 26,
        DialStringInvalid = 27,
        NoNetwork = 30,
        NetworkTimeout = 31,
        NetworkNotAllowed = 32,
        NetworkPin = 40,
        NetworkPuk = 41,
        NetworkSubsetPin = 42,
        NetworkSubsetPuk = 43,
        ServicePin = 44,
        ServicePuk = 45,
        CorpPin = 46,
        CorpPuk = 47,
        HiddenKeyRequired = 48,
        EapMethodNotSupported = 49,
        IncorrectParameters = 50,
        CommandDisabled = 51,
        CommandAborted = 52,
        NotAttachedRestricted = 53,
        NotAllowedEmergencyOnly = 54,
        NotAllowedRestricted = 55,
        FixedDialNumberOnly = 56,
        TemporarilyOutOfService = 57,
        LanguageOrAlphabetNotSupported = 58,
        UnexpectedDataValue = 59,
        SystemFailure = 60,
        DataMissing = 61,
        CallBarred = 62,
        MessageWaitingIndicationSubscriptionFailure = 63,
        Unknown = 100,
        ImsiUnknownInHss = 102,
        IllegalUe = 103,
        ImsiUnknownInVlr = 104,
        ImeiNotAccepted = 105,
        IllegalMe = 106,
        PsServicesNotAllowed = 107,
        PsAndNonPsServicesNotAllowed = 108,
        UeIdentityNotDerivedFromNetwork = 109,
        ImplicitlyDetached = 110,
        PlmnNotAllowed = 111,
        AreaNotAllowed = 112,
        RoamingNotAllowedInArea = 113,
        PsServicesNotAllowedInPlmn = 114,
        NoCellsInArea = 115,
        MscTemporarilyNotReachable = 116,
        NetworkFailureAttach = 117,
        CsDomainUnavailable = 118,
        EsmFailure = 119,
        Congestion = 122,
        MbmsBearerCapabilitiesInsufficientForService = 124,
        NotAuthorizedForCsg = 125,
        InsufficientResources = 126,
        MissingOrUnknownApn = 127,
        UnknownPdpAddressOrType = 128,
        UserAuthenticationFailed = 129,
        ActivationRejectedByGgsnOrGw = 130,
        ActivationRejectedUnspecified = 131,
        ServiceOptionNotSupported = 132,
        ServiceOptionNotSubscribed = 133,
        ServiceOptionOutOfOrder = 134,
        NsapiOrPtiAlreadyInUse = 135,
        RegularDeactivation = 136,
        QosNotAccepted = 137,
        CallCannotBeIdentified = 138,
        CsServiceTemporarilyUnavailable = 139,
        FeatureNotSupported = 140,
        SemanticErrorInTftOperation = 141,
        SyntacticalErrorInTftOperation = 142,
        UnknownPdpContext = 143,
        SemanticErrorsInPacketFilter = 144,
        SyntacticalErrorInPacketFilter = 145,
        PdpContextWithoutTftAlreadyActivated = 146,
        MulticastGroupMembershipTimeout = 147,
        GprsUnknown = 148,
        PdpAuthFailure = 149,
        InvalidMobileClass = 150,
        LastPdnDisconnectionNotAllowedLegacy = 151,
        LastPdnDisconnectionNotAllowed = 171,
        SemanticallyIncorrectMessage = 172,
        InvalidMandatoryInformation = 173,
        MessageTypeNotImplemented = 174,
        ConditionalIeError = 175,
        UnspecifiedProtocolError = 176,
        OperatorDeterminedBarring = 177,
        MaximumNumberOfBearersReached = 178,
        RequestedApnNotSupported = 179,
        RequestRejectedBcmViolation = 180,
        UnsupportedQciOr5QiValue = 181,
        UserDataViaControlPlaneCongested = 182,
        SmsProvidedViaGprsInRoutingArea = 183,
        InvalidPtiValue = 184,
        NoBearerActivated = 185,
        MessageNotCompatibleWithProtocolState = 186,
        RecoveryOnTimerExpiry = 187,
        InvalidTransactionIdValue = 188,
        ServiceOptionNotAuthorizedInPlmn = 189,
        NetworkFailureActivation = 190,
        ReactivationRequested = 191,
        Ipv4OnlyAllowed = 192,
        Ipv6OnlyAllowed = 193,
        SingleAddressBearersOnlyAllowed = 194,
        CollisionWithNetworkInitiatedRequest = 195,
        Ipv4V6OnlyAllowed = 196,
        NonIpOnlyAllowed = 197,
        BearerHandlingUnsupported = 198,
        ApnRestrictionIncompatible = 199,
        MultipleAccessToPdnConnectionNotAllowed = 200,
        EsmInformationNotReceived = 201,
        PdnConnectionNonexistent = 202,
        MultiplePdnConnectionSameApnNotAllowed = 203,
        SevereNetworkFailure = 204,
        InsufficientResourcesForSliceAndDnn = 205,
        UnsupportedSscMode = 206,
        InsufficientResourcesForSlice = 207,
        MessageTypeNotCompatibleWithProtocolState = 208,
        IeNotImplemented = 209,
        N1ModeNotAllowed = 210,
        RestrictedServiceArea = 211,
        LadnUnavailable = 212,
        MissingOrUnknownDnnInSlice = 213,
        NgksiAlreadyInUse = 214,
        PayloadNotForwarded = 215,
        Non3GppAccessTo5GcnNotAllowed = 216,
        ServingNetworkNotAuthorized = 217,
        DnnNotSupportedInSlice = 218,
        InsufficientUserPlaneResourcesForPduSessio = 219,
        OutOfLadnServiceArea = 220,
        PtiMismatch = 221,
        MaxDataRateForUserPlaneIntegrityTooLow = 222,
        SemanticErrorInQosOperation = 223,
        SyntacticalErrorInQosOperation = 224,
        InvalidMappedEpsBearerIdentity = 225,
        RedirectionTo5GcnRequired = 226,
        RedirectionToEpcRequired = 227,
        TemporarilyUnauthorizedForSnpn = 228,
        PermanentlyUnauthorizedForSnpn = 229,
        EthernetOnlyAllowed = 230,
        UnauthorizedForCag = 231,
        NoNetworkSlicesAvailable = 232,
        WirelineAccessAreaNotAllowed = 233,
    };

    class Details {
      public:
        using Record = Utils::EnumStringRecord<Code>;

        inline static constexpr std::array map = {
            Record{"0", Code::PhoneFailure},
            Record{"1", Code::NoConnection},
            Record{"10", Code::SimNotInserted},
            Record{"100", Code::Unknown},
            Record{"102", Code::ImsiUnknownInHss},
            Record{"103", Code::IllegalUe},
            Record{"104", Code::ImsiUnknownInVlr},
            Record{"105", Code::ImeiNotAccepted},
            Record{"106", Code::IllegalMe},
            Record{"107", Code::PsServicesNotAllowed},
            Record{"108", Code::PsAndNonPsServicesNotAllowed},
            Record{"109", Code::UeIdentityNotDerivedFromNetwork},
            Record{"11", Code::SimPin},
            Record{"110", Code::ImplicitlyDetached},
            Record{"111", Code::PlmnNotAllowed},
            Record{"112", Code::AreaNotAllowed},
            Record{"113", Code::RoamingNotAllowedInArea},
            Record{"114", Code::PsServicesNotAllowedInPlmn},
            Record{"115", Code::NoCellsInArea},
            Record{"116", Code::MscTemporarilyNotReachable},
            Record{"117", Code::NetworkFailureAttach},
            Record{"118", Code::CsDomainUnavailable},
            Record{"119", Code::EsmFailure},
            Record{"12", Code::SimPuk},
            Record{"122", Code::Congestion},
            Record{"124", Code::MbmsBearerCapabilitiesInsufficientForService},
            Record{"125", Code::NotAuthorizedForCsg},
            Record{"126", Code::InsufficientResources},
            Record{"127", Code::MissingOrUnknownApn},
            Record{"128", Code::UnknownPdpAddressOrType},
            Record{"129", Code::UserAuthenticationFailed},
            Record{"13", Code::SimFailure},
            Record{"130", Code::ActivationRejectedByGgsnOrGw},
            Record{"131", Code::ActivationRejectedUnspecified},
            Record{"132", Code::ServiceOptionNotSupported},
            Record{"133", Code::ServiceOptionNotSubscribed},
            Record{"134", Code::ServiceOptionOutOfOrder},
            Record{"135", Code::NsapiOrPtiAlreadyInUse},
            Record{"136", Code::RegularDeactivation},
            Record{"137", Code::QosNotAccepted},
            Record{"138", Code::CallCannotBeIdentified},
            Record{"139", Code::CsServiceTemporarilyUnavailable},
            Record{"14", Code::SimBusy},
            Record{"140", Code::FeatureNotSupported},
            Record{"141", Code::SemanticErrorInTftOperation},
            Record{"142", Code::SyntacticalErrorInTftOperation},
            Record{"143", Code::UnknownPdpContext},
            Record{"144", Code::SemanticErrorsInPacketFilter},
            Record{"145", Code::SyntacticalErrorInPacketFilter},
            Record{"146", Code::PdpContextWithoutTftAlreadyActivated},
            Record{"147", Code::MulticastGroupMembershipTimeout},
            Record{"148", Code::GprsUnknown},
            Record{"149", Code::PdpAuthFailure},
            Record{"15", Code::SimWrong},
            Record{"150", Code::InvalidMobileClass},
            Record{"151", Code::LastPdnDisconnectionNotAllowedLegacy},
            Record{"16", Code::IncorrectPassword},
            Record{"17", Code::SimPin2},
            Record{"171", Code::LastPdnDisconnectionNotAllowed},
            Record{"172", Code::SemanticallyIncorrectMessage},
            Record{"173", Code::InvalidMandatoryInformation},
            Record{"174", Code::MessageTypeNotImplemented},
            Record{"175", Code::ConditionalIeError},
            Record{"176", Code::UnspecifiedProtocolError},
            Record{"177", Code::OperatorDeterminedBarring},
            Record{"178", Code::MaximumNumberOfBearersReached},
            Record{"179", Code::RequestedApnNotSupported},
            Record{"18", Code::SimPuk2},
            Record{"180", Code::RequestRejectedBcmViolation},
            Record{"181", Code::UnsupportedQciOr5QiValue},
            Record{"182", Code::UserDataViaControlPlaneCongested},
            Record{"183", Code::SmsProvidedViaGprsInRoutingArea},
            Record{"184", Code::InvalidPtiValue},
            Record{"185", Code::NoBearerActivated},
            Record{"186", Code::MessageNotCompatibleWithProtocolState},
            Record{"187", Code::RecoveryOnTimerExpiry},
            Record{"188", Code::InvalidTransactionIdValue},
            Record{"189", Code::ServiceOptionNotAuthorizedInPlmn},
            Record{"190", Code::NetworkFailureActivation},
            Record{"191", Code::ReactivationRequested},
            Record{"192", Code::Ipv4OnlyAllowed},
            Record{"193", Code::Ipv6OnlyAllowed},
            Record{"194", Code::SingleAddressBearersOnlyAllowed},
            Record{"195", Code::CollisionWithNetworkInitiatedRequest},
            Record{"196", Code::Ipv4V6OnlyAllowed},
            Record{"197", Code::NonIpOnlyAllowed},
            Record{"198", Code::BearerHandlingUnsupported},
            Record{"199", Code::ApnRestrictionIncompatible},
            Record{"2", Code::LinkReserved},
            Record{"20", Code::MemoryFull},
            Record{"200", Code::MultipleAccessToPdnConnectionNotAllowed},
            Record{"201", Code::EsmInformationNotReceived},
            Record{"202", Code::PdnConnectionNonexistent},
            Record{"203", Code::MultiplePdnConnectionSameApnNotAllowed},
            Record{"204", Code::SevereNetworkFailure},
            Record{"205", Code::InsufficientResourcesForSliceAndDnn},
            Record{"206", Code::UnsupportedSscMode},
            Record{"207", Code::InsufficientResourcesForSlice},
            Record{"208", Code::MessageTypeNotCompatibleWithProtocolState},
            Record{"209", Code::IeNotImplemented},
            Record{"21", Code::InvalidIndex},
            Record{"210", Code::N1ModeNotAllowed},
            Record{"211", Code::RestrictedServiceArea},
            Record{"212", Code::LadnUnavailable},
            Record{"213", Code::MissingOrUnknownDnnInSlice},
            Record{"214", Code::NgksiAlreadyInUse},
            Record{"215", Code::PayloadNotForwarded},
            Record{"216", Code::Non3GppAccessTo5GcnNotAllowed},
            Record{"217", Code::ServingNetworkNotAuthorized},
            Record{"218", Code::DnnNotSupportedInSlice},
            Record{"219", Code::InsufficientUserPlaneResourcesForPduSessio},
            Record{"22", Code::NotFound},
            Record{"220", Code::OutOfLadnServiceArea},
            Record{"221", Code::PtiMismatch},
            Record{"222", Code::MaxDataRateForUserPlaneIntegrityTooLow},
            Record{"223", Code::SemanticErrorInQosOperation},
            Record{"224", Code::SyntacticalErrorInQosOperation},
            Record{"225", Code::InvalidMappedEpsBearerIdentity},
            Record{"226", Code::RedirectionTo5GcnRequired},
            Record{"227", Code::RedirectionToEpcRequired},
            Record{"228", Code::TemporarilyUnauthorizedForSnpn},
            Record{"229", Code::PermanentlyUnauthorizedForSnpn},
            Record{"23", Code::MemoryFailure},
            Record{"230", Code::EthernetOnlyAllowed},
            Record{"231", Code::UnauthorizedForCag},
            Record{"232", Code::NoNetworkSlicesAvailable},
            Record{"233", Code::WirelineAccessAreaNotAllowed},
            Record{"24", Code::TextTooLong},
            Record{"25", Code::InvalidChars},
            Record{"26", Code::DialStringTooLong},
            Record{"27", Code::DialStringInvalid},
            Record{"3", Code::NotAllowed},
            Record{"30", Code::NoNetwork},
            Record{"31", Code::NetworkTimeout},
            Record{"32", Code::NetworkNotAllowed},
            Record{"4", Code::NotSupported},
            Record{"40", Code::NetworkPin},
            Record{"41", Code::NetworkPuk},
            Record{"42", Code::NetworkSubsetPin},
            Record{"43", Code::NetworkSubsetPuk},
            Record{"44", Code::ServicePin},
            Record{"45", Code::ServicePuk},
            Record{"46", Code::CorpPin},
            Record{"47", Code::CorpPuk},
            Record{"48", Code::HiddenKeyRequired},
            Record{"49", Code::EapMethodNotSupported},
            Record{"5", Code::PhSimPin},
            Record{"50", Code::IncorrectParameters},
            Record{"51", Code::CommandDisabled},
            Record{"52", Code::CommandAborted},
            Record{"53", Code::NotAttachedRestricted},
            Record{"54", Code::NotAllowedEmergencyOnly},
            Record{"55", Code::NotAllowedRestricted},
            Record{"56", Code::FixedDialNumberOnly},
            Record{"57", Code::TemporarilyOutOfService},
            Record{"58", Code::LanguageOrAlphabetNotSupported},
            Record{"59", Code::UnexpectedDataValue},
            Record{"6", Code::PhFsimPin},
            Record{"60", Code::SystemFailure},
            Record{"61", Code::DataMissing},
            Record{"62", Code::CallBarred},
            Record{"63", Code::MessageWaitingIndicationSubscriptionFailure},
            Record{"7", Code::PhFsimPuk}};

        static_assert(Utils::isStrictlySortedByString(map),
                      "CmeError map must be sorted by string and shall not contain duplicates!");

        inline static constexpr auto converter = Utils::EnumStringConverter{map};
    };

    Core::Enum<Code> code{};

    CmeError() : Core::AResponse("+CME ERROR: ") {}
    ~CmeError() = default;
    void accept(Core::AInputVisitor &visitor) override {
        APacket::accept(visitor, code);
    }
};

} // namespace Std
} // namespace Proto
} // namespace ATL_NS

template <>
struct ATL_NS::Core::EnumTraits<ATL_NS::Proto::Std::CmeError::Code> {
    using Code = Proto::Std::CmeError::Code;

    static constexpr const char *toString(Code value) {
        return Proto::Std::CmeError::Details::converter.toString(value).data();
    }

    static std::optional<Code> fromString(const char *str) {
        return Proto::Std::CmeError::Details::converter.fromString(str);
    }
};